apiVersion: security.istio.io/v1
kind: AuthorizationPolicy
metadata:
  name: allow-to-storefront-bff
  namespace: dev
spec:
  selector:
    matchLabels:
      app: storefront-bff
  action: ALLOW
  rules:
    - from:
        - source:
            namespaces:
              - dev

